 
 /*------------------------------------------------------------------------
    File        : CommonObj
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : demo
    Created     : Tue Oct 10 09:50:08 EEST 2017
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS CommonObj ABSTRACT: 

END CLASS.